---
swagger: "2.0"
info:
  description: Application for buying and selling assets
  version: 1.0.0
  title: Trust Brix
  contact:
    email: developers@trustbrix.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: virtserver.swaggerhub.com
tags:
- name: Register
  description: Registration for new user
- name: Authentication
  description: Authentication contains login,forget password and so on
schemes:
- https
paths:
  /get-user/{id}:
    get:
      tags:
      - Register
      summary: Get a user by id
      description: |
        Get a user by id
      operationId: Get user
      produces:
      - application/json
      parameters:
      - name: id
        in: query
        description: ID of user for retrive
        required: true
      responses:
        200:
          description: Search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/UserItem'
        400:
          description: bad input parameter
  /register:
    post:
      tags:
      - Register
      summary: Create a new user
      description: To create a new user
      operationId: register the user
      produces:
      - application/json
      parameters:
      - in: body
        name: login items
        description: username and password for login
        required: false
        schema:
          $ref: '#/definitions/InventoryItem'
      responses:
        200:
          description: Search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/UserItem'
        400:
          description: bad input parameter
  /login:
    post:
      tags:
      - Authentication
      summary: Login
      description: To authenticate the user
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: login items
        description: username and password for login
        required: false
        schema:
          $ref: '#/definitions/InventoryItem'
      responses:
        201:
          description: item created
        400:
          description: invalid input, object invalid
        409:
          description: an existing item already exists
definitions:
  UserItem:
    type: object
    required:
    - data
    - message
    - status
    - success
    properties:
      success:
        type: string
        example: "true"
      status:
        type: number
        example: 200.0
      message:
        type: string
        example: Successfully retrived..
      data:
        type: object
        example:
          tosAccepted: false
          emailVerified: false
          _id: 5cae3ffd6967601f00ff498b
          firstname: test3
          lastname: test3
          email: test@gmail.com
          password: $2b$10$TyXVBUv
          imageLink: src/images/picture1.jpeg
        properties: {}
  registrationInput:
    type: object
    required:
    - data
    properties:
      data:
        type: object
        example:
          tosAccepted: false
          emailVerified: false
          _id: 5cae3ffd6967601f00ff498b
          firstname: test3
          lastname: test3
          email: test@gmail.com
          password: $2b$10$TyXVBUvWB2rdv.FpZPb71u7xJnFgdzkus937tLHYeNr5ZSx9iobv
          imageLink: src/images/picture1.jpeg
          mobile: "1231212311"
          userType: Admin
          __v: 0
        properties: {}
  InventoryItem:
    type: object
    required:
    - manufacturer
    - name
    - releaseDate
    properties:
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      name:
        type: string
        example: Widget Adapter
      releaseDate:
        type: string
        format: date-time
        example: 2016-08-29T09:12:33.001Z
      manufacturer:
        $ref: '#/definitions/Manufacturer'
  Manufacturer:
    required:
    - name
    properties:
      name:
        type: string
        example: ACME Corporation
      homePage:
        type: string
        format: url
        example: https://www.acme-corp.com
      phone:
        type: string
        example: 408-867-5309
